module.exports = {
		development:{
				mysql:{
					host:process.env.DEV_MYSQL_HOST?process.env.DEV_MYSQL_HOST:'localhost',
					port:process.env.DEV_MYSQL_PORT?process.env.DEV_MYSQL_PORT:3306,
					user:process.env.DEV_MYSQL_USER?process.env.DEV_MYSQL_USER:'root',
					password:process.env.DEV_MYSQL_PASSWORD?process.env.DEV_MYSQL_PASSWORD:'',
					database:process.env.DEV_MYSQL_DATABASE?process.env.DEV_MYSQL_DATABASE:''
				},
		},
		production:{
				mysql:{
					host:process.env.MYSQL_HOST?process.env.MYSQL_HOST:'localhost',
					port:process.env.MYSQL_PORT?process.env.MYSQL_PORT:3306,
					user:process.env.MYSQL_USER?process.env.MYSQL_USER:'root',
					password:process.env.MYSQL_PASSWORD?process.env.MYSQL_PASSWORD:'',
					database:process.env.MYSQL_DATABASE?process.env.MYSQL_DATABASE:''
				}
		},
		test:{
			mysql:{
					host:process.env.TEST_MYSQL_HOST?process.env.TEST_MYSQL_HOST:'localhost',		
					port:process.env.TEST_MYSQL_PORT?process.env.TEST_MYSQL_PORT:3306,
					user:process.env.TEST_MYSQL_USER?process.env.TEST_MYSQL_USER:'root',
					password:process.env.TEST_MYSQL_PASSWORD?process.env.TEST_MYSQL_PASSWORD:'',
					database:process.env.TEST_MYSQL_DATABASE?process.env.TEST_MYSQL_DATABASE:''
				}
			}
	};
